### PR TITLE
Bump up dependency gems version

### PR DESCRIPTION
**Pull request by soartec-lab**
Thank you for making this wonderful gem.

## Summary

I'm actually using this gem in my rails project. I created this PR because I found a problem when I upgraded rails to 6.1.

```
Bundler could not find compatible versions for gem "thor":
  In Gemfile:
    docker-fluent-logger was resolved to 1.0.0, which depends on
      thor (~> 0.19)

    rails (~> 6.1) was resolved to 6.1.0, which depends on
      railties (= 6.1.0) was resolved to 6.1.0, which depends on
        thor (~> 1.0)
```

### Ruby version
```
$ ruby -v
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux-musl]
```

### 1. rails version in Gemfile

```
gem 'rails', '~> 6.1'
```

### 2. execcute command `bundle update`

```
$ bundle update
```

### CODE REVIEW

**Comment by soartec-lab** [comment]
@naomichi-y
I'm in trouble because this PR isn't merged. Could you PR review?

**Review by naomichi-y — APPROVED** [review]
thank you!
LGTM

**Comment by soartec-lab** [comment]
@naomichi-y 
Thanks!!
Please also publish to rubygems 🚀

**Comment by naomichi-y** [comment]
@soartec-lab released!
https://rubygems.org/gems/docker-fluent-logger/versions/1.0.1

**Comment by soartec-lab** [comment]
Thanks !!

**Pull request merged**
